name: Fetch and publish data.csv

# Trigger the workflow on a schedule
on:
  workflow_dispatch:
  schedule:
    # Run at 6:30 AM and 6:30 PM UTC every day
    - cron: '30 6,18 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository to get access to the Python script
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # specify version if necessary, e.g., '3.9'

      # Step 3: Install dependencies if any are specified in requirements.txt
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      # Step 4: Run the Python script to export the data.csv file
      - name: Export csv
        run: python src/export_data.py && mkdir -p pages && mv data.csv pages

      - name: Upload static files as artifact
        id: data-publish
        uses: actions/upload-pages-artifact@v3
        with:
          path: pages

  # Deploy job
  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: data-publish
        uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action
